client:
  # Client config
  model: ConvNet
  
  # Trainer config
  trainer:
    optimizer:
      class: SGD
      lr: .01
      weight_decay: 0
      momentum: .9
    batch_size: 16
    loss_fn: CrossEntropyLoss
    n_epochs: 3
  
  # Aggregator config
  aggregator:
    policy:
      name: FedAvg
  
  # Selector config
  selector:
    policy:
      name: Full

  # Activator config
  activator:
    policy:
      name: Full